<?php

/***************************************************************
 * Extension Manager/Repository config file for ext "extensible_sitemap".
 *
 * Auto generated 01-07-2013 16:20
 *
 * Manual updates:
 * Only the data in the array - everything else is removed by next
 * writing. "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => 'extensible sitemap',
	'description' => 'Generate a sitemap xml file for use by search engines like google. It is extensible, so you can easily link pages generated by your own extensions.',
	'category' => 'fe',
	'shy' => 0,
	'version' => '0.2.0',
	'dependencies' => '',
	'conflicts' => '',
	'priority' => '',
	'loadOrder' => '',
	'module' => '',
	'state' => 'beta',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => 'pages',
	'clearcacheonload' => 0,
	'lockType' => '',
	'author' => 'Christian Zenker',
	'author_email' => 'christian.zenker@599media.de',
	'author_company' => '599media GmbH',
	'CGLcompliance' => NULL,
	'CGLcompliance_note' => NULL,
	'constraints' => 
	array (
		'depends' => 
		array (
		),
		'conflicts' => '',
		'suggests' => 
		array (
		),
	),
);

?>