<?php
$EM_CONF[$_EXTKEY] = array(
	'title' => 'extensible sitemap',
	'description' => 'Generate a sitemap xml file for use by search engines like google. It is extensible, so you can easily link pages generated by your own extensions.',
	'category' => 'fe',
	'shy' => 0,
	'version' => '0.1.0',
	'dependencies' => '',
	'conflicts' => '',
	'priority' => '',
	'loadOrder' => '',
	'module' => '',
	'state' => 'beta',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => 'pages',
	'clearcacheonload' => 0,
	'lockType' => '',
	'author' => 'Christian Zenker',
	'author_email' => 'christian.zenker@599media.de',
	'author_company' => '599media GmbH',
	'CGLcompliance' => '',
	'CGLcompliance_note' => '',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'_md5_values_when_last_written' => '',
);

?>
